### PR TITLE
Add Dockerfile for building

### PR DESCRIPTION
**Pull request by evq**
This is the Dockerfile I use for building

### CODE REVIEW

**Comment by posix4e** [comment]
Seems mostly legit. Do we need a CMD?

**Comment by posix4e** [comment]
Also we can probably just call it .Dockerfile and have a script for launching the docker shell. Either way though.

**Comment by posix4e** [comment]
@evq  how'd we test?

**Comment by posix4e** [comment]
Why dockerignore everything?

**Comment by evq** [comment]
@posix4e 
script to launch / rename sound legit.

yeah I had previously not built muon in my work vm (only in personal vm) and did a fresh build starting just from a Dockerfile (I added sccache later on, but I don't think I changed any of the core deps).

dockerignore everything to speed up the docker build process since we don't use anything other than Dockerfile during build. browser-laptop-bootstrap can be quite large and by default during the docker build it gets tar'd and uploaded over the rest api

**Comment by posix4e** [comment]
I don't buy that more that src needs to be ignored.

**Comment by evq** [comment]
i'm fine with just ignoring src, the other stuff is peanuts compared to it. doesn't really matter atm since neither `ADD` or `COPY` is used in the Dockerfile

**Comment by posix4e** [comment]
@evq True, just otherwise confusing. Also I assume it's in the gitignore anyway. Otherwise good to go

**Comment by ayumi** [comment]
I've updated this based on feedback

@evq @posix4e please have another look

**Pull request merged**
